title: "CMS MVC Web Application"
description: "CMS MVC Web Application Framework"
author: "Kitisak (Fluke) Sapphaniran"
mode: "DEV"
pepper_key: "Zr8UiJQvWE"
driver:
  mysql:
    production:
      name: "getnaprg_database"
      user: "getnaprg_database"
      password: "@Fluke160941"
      host: "localhost"
      port: 3306
    develope: 
      name: "getprog_db"
      user: "root"
      password: "@Fluke160941"
      host: "localhost"
      port: 3306
  ftp:
    domain: "ovh1.getnaprog.com"
    hostname: "getnaprog.com"
    username: "ovh1@getnaprog.com"
    password: "uY7k3.#yZNH48y"
    mode: "passive"
    ssl: "false"
    port: 21
    timeout: 30
api:
  drive: "Drive_BXQtPmpEv0gcFnei7CQvTxAcKTHyDkHviTTK8TRC"
  data: "Data_cY0Mac5wPW5ITTiih2bdePksW5qMYozhhHHdtnop"




