title: "CMS MVC Web Application"
description: "CMS MVC Web Application Framework"
author: "Kitisak (Fluke) Sapphaniran"
mode: "DEV"
driver:
  mysql:
    production:
      name: "getnapro_db"
      user: "getnapro_db"
      password: "@Fluke160941"
      host: "localhost"
      port: 3306
    develope: 
      name: "getprog_db"
      user: "root"
      password: "@Fluke160941"
      host: "localhost"
      port: 3306
api:
  drive: "Drive_BXQtPmpEv0gcFnei7CQvTxAcKTHyDkHviTTK8TRC"
  data: "Data_cY0Mac5wPW5ITTiih2bdePksW5qMYozhhHHdtnop"


