title: "MVC fast and light weight"
description: "MVC fast and light weight"
author: "webmaster"
mode: "DEV"
pepper_key: "l5PdN23NtafWhsi" # OPTIONAL: Random pepper key
driver:
  mysql:
    production:
      name: "prod_db"
      user: "root"
      password: "123ZXCasd!@#"
      host: "localhost"
      port: 3306
    develope: 
      name: "pg"
      user: "root"
      password: "123ZXCasd!@#"
      host: "localhost"
      port: 3306
  ftp:
    domain: "mydomain"
    hostname: "myhostname"
    username: "myusername"
    password: "password"
    mode: "passive"
    ssl: "false"
    port: 21
    timeout: 30



